### ISSUE TITLE
GetStudent could be implemented better

### ISSUE THREAD

**Issue by A-Soltani** [MajidParsa/StudentManaging#4]
https://github.com/MajidParsa/StudentManaging/blob/546b554ec0b1a93428ac47799cfd112ac34d052c/StudentManaging.Infrastructure/Repositories/EF/StudentManagement/StudentRepository.cs#L20

would be better to use the following code:

public async Task<Student> Get(int id) => 
            await _context.Students.FirstOrDefaultAsync(s => s.Id == id );

**Comment by MajidParsa** [comment]
We want to retrieve a list of students so FirstOrDefault method is not suitable.
I changed it:
        public async Task<IEnumerable<Student>> Get(int? id) =>
	        await _context.Students.Where(s => s.Id == id || id.HasValue == false).ToListAsync();
