### ISSUE TITLE
UpdateStudent would be better not to be static method

### ISSUE THREAD

**Issue by A-Soltani** [MajidParsa/StudentManaging#5]
https://github.com/MajidParsa/StudentManaging/blob/546b554ec0b1a93428ac47799cfd112ac34d052c/StudentManaging.Domain/AggregatesModel/StudentAggregate/Student.cs#L29

public void UpdateStudent(string name, Address address, string phoneNumber)
        {
            Name = name;
            Address = address;
            PhoneNumber = phoneNumber;
        }

**Comment by MajidParsa** [comment]
I can't understand this issue
